services:
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: dockgraph-backend
    command: python -m uvicorn api.chat:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - ./Server/.env 

    develop:
      watch:
        - action: sync
          path: ./Server
          target: /app
        - action: restart
          path: ./Server

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dockgraph-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /src

